title: Git Notes
description: 记录代码、工具与工程实践
lang: zh-CN
timezone: Asia/Shanghai

theme: minima
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

header_pages:
  - about.md

plugins:
  - jekyll-feed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
